In [1]:
import pandas as pd
import re

path = './052018_plate1/Results-Nuc-'
WELLS = ['B0{}'.format(k) for k in range(2, 5)]
FIELD = ['fld{}'.format(k) for k in range(1, 10)]

files_Nuc = [path + '{}{}.txt'.format(w, f) 
              for w in WELLS for f in FIELD]

df_Nuc = [pd.read_csv(file, sep='\t', 
                 engine='python', 
                 usecols=['Label', 'Area', 'IntDen']) 
           for file in files_Nuc]

n = len(df_Nuc)
len(WELLS), len(FIELD), len(df_Nuc)

(3, 9, 27)

In [2]:
for df in df_Nuc:
    print('\n', '* ' * 26, '\n')
    print(df.head(10))

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld1:0001-0031:DAPI-0001  166.410   450411.746
1  B02_fld1:0002-0033:DAPI-0001   92.545   250158.089
2  B02_fld1:0003-0032:DAPI-0001  145.185   470850.506
3  B02_fld1:0004-0029:DAPI-0001   82.356   171596.262
4  B02_fld1:0005-0033:DAPI-0001  273.388  1090953.285
5  B02_fld1:0006-0030:DAPI-0001   73.017   195095.784
6  B02_fld1:0007-0031:DAPI-0001  118.865   535500.086
7  B02_fld1:0008-0033:DAPI-0001  238.578  1154179.887
8  B02_fld1:0009-0034:DAPI-0001  320.934  1048435.435
9  B02_fld1:0010-0031:DAPI-0001  142.637   731758.196

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld2:0001-0027:DAPI-0001  108.676  1244034.696
1  B02_fld2:0002-0028:DAPI-0001   54.338   240530.910
2  B02_fld2:0003-0031:DAPI-0001   93.394   391233.331
3  B02_fld2:0004-0034:DAPI-0001  257.257   937947.439
4  B02_fld2:0005-0031:DAPI-0001   95.941   157731.561
5  B02_fld2:0006-0036:DAPI-0001  142.637   704576.420
6  B02_fld2:0007-0041:DAPI-0001  219.899  1498138.239
7  B02_fld2:0008-0035:DAPI-0001  119.714   493348.169
8  B02_fld2:0009-0039:DAPI-0001  119.714   372769.421
9  B02_fld2:0010-0038:DAPI-0001  103.582   254687.678

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld3:0001-0027:DAPI-0001   43.301   288791.616
1  B02_fld3:0002-0032:DAPI-0001  164.712  1328104.197
2  B02_fld3:0003-0036:DAPI-0001  190.183  1057935.260
3  B02_fld3:0004-0031:DAPI-0001   89.148   313979.014
4  B02_fld3:0005-0031:DAPI-0001  105.280   495186.325
5  B02_fld3:0006-0034:DAPI-0001  116.317   472214.901
6  B02_fld3:0007-0030:DAPI-0001   77.262   184250.243
7  B02_fld3:0008-0037:DAPI-0001  163.014   826505.130
8  B02_fld3:0009-0033:DAPI-0001  135.845   478079.169
9  B02_fld3:0010-0031:DAPI-0001   46.697   136228.115

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld4:0001-0034:DAPI-0001  268.294  1395258.423
1  B02_fld4:0002-0031:DAPI-0001  361.688  2266032.108
2  B02_fld4:0003-0029:DAPI-0001   76.413   216584.797
3  B02_fld4:0004-0033:DAPI-0001  172.354  1065205.525
4  B02_fld4:0005-0030:DAPI-0001   95.941   400430.051
5  B02_fld4:0006-0037:DAPI-0001  204.617   433561.847
6  B02_fld4:0007-0034:DAPI-0001  222.447   532668.563
7  B02_fld4:0008-0035:DAPI-0001  203.768   503988.245
8  B02_fld4:0009-0028:DAPI-0001   50.093   106361.699
9  B02_fld4:0010-0030:DAPI-0001   65.376   160938.357

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld5:0001-0030:DAPI-0001  176.599   561961.033
1  B02_fld5:0002-0028:DAPI-0001   89.997   399827.238
2  B02_fld5:0003-0041:DAPI-0001  456.779  3250350.306
3  B02_fld5:0004-0030:DAPI-0001  173.203  1380659.309
4  B02_fld5:0005-0029:DAPI-0001   56.036   197871.271
5  B02_fld5:0006-0041:DAPI-0001  455.081  3416747.093
6  B02_fld5:0007-0037:DAPI-0001  301.407  2304663.936
7  B02_fld5:0008-0043:DAPI-0001  218.201  1164959.204
8  B02_fld5:0009-0043:DAPI-0001  132.449  1033523.877
9  B02_fld5:0010-0052:DAPI-0001  303.105  1180324.994

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld6:0001-0035:DAPI-0001  412.630  2740816.181
1  B02_fld6:0002-0031:DAPI-0001  234.333   980918.672
2  B02_fld6:0003-0042:DAPI-0001  620.643  3750803.179
3  B02_fld6:0004-0030:DAPI-0001  178.297  1123081.524
4  B02_fld6:0005-0029:DAPI-0001   96.790   489284.700
5  B02_fld6:0006-0029:DAPI-0001   84.903   281155.417
6  B02_fld6:0007-0035:DAPI-0001  210.560  1532201.424
7  B02_fld6:0008-0033:DAPI-0001  121.412   528801.220
8  B02_fld6:0009-0033:DAPI-0001  149.430  2607186.105
9  B02_fld6:0010-0034:DAPI-0001  109.525   691347.644

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld7:0001-0030:DAPI-0001  376.970  1553363.559
1  B02_fld7:0002-0036:DAPI-0001  325.179  4507605.287
2  B02_fld7:0003-0028:DAPI-0001   66.225   154967.112
3  B02_fld7:0004-0026:DAPI-0001   52.640   171081.749
4  B02_fld7:0005-0027:DAPI-0001  108.676   619858.258
5  B02_fld7:0006-0031:DAPI-0001  157.920   815239.317
6  B02_fld7:0007-0029:DAPI-0001   94.243   443255.251
7  B02_fld7:0008-0026:DAPI-0001   85.752   447468.150
8  B02_fld7:0009-0029:DAPI-0001   72.168   154517.973
9  B02_fld7:0010-0026:DAPI-0001   68.772   356582.616

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld8:0001-0027:DAPI-0001   92.545  1126441.995
1  B02_fld8:0002-0032:DAPI-0001  367.631  2395408.530
2  B02_fld8:0003-0028:DAPI-0001  145.185  1680668.342
3  B02_fld8:0004-0024:DAPI-0001   53.489   264038.922
4  B02_fld8:0005-0025:DAPI-0001   42.452   130905.530
5  B02_fld8:0006-0030:DAPI-0001  169.807   985452.506
6  B02_fld8:0007-0030:DAPI-0001  199.523   856241.644
7  B02_fld8:0008-0027:DAPI-0001   94.243   645608.565
8  B02_fld8:0009-0029:DAPI-0001  149.430   965544.391
9  B02_fld8:0010-0026:DAPI-0001   85.752   370769.950

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B02_fld9:0001-0032:DAPI-0001  292.916  1341812.676
1  B02_fld9:0002-0028:DAPI-0001  122.261   599526.477
2  B02_fld9:0003-0031:DAPI-0001  193.579  1002047.695
3  B02_fld9:0004-0027:DAPI-0001  139.241  1125300.046
4  B02_fld9:0005-0029:DAPI-0001   79.809   548677.071
5  B02_fld9:0006-0034:DAPI-0001  134.147   491625.482
6  B02_fld9:0007-0038:DAPI-0001  349.801  2168608.174
7  B02_fld9:0008-0041:DAPI-0001  300.558  2438736.357
8  B02_fld9:0009-0037:DAPI-0001  140.090   102060.500
9  B02_fld9:0010-0040:DAPI-0001   79.809   648137.833

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld1:0001-0039:DAPI-0001  324.330   792661.845
1  B03_fld1:0002-0032:DAPI-0001  157.920   602391.112
2  B03_fld1:0003-0034:DAPI-0001  179.146   819851.262
3  B03_fld1:0004-0029:DAPI-0001   67.074   211967.758
4  B03_fld1:0005-0036:DAPI-0001  253.012  1150742.155
5  B03_fld1:0006-0032:DAPI-0001  187.636   516182.898
6  B03_fld1:0007-0032:DAPI-0001   86.601   192612.364
7  B03_fld1:0008-0036:DAPI-0001  347.254   948836.281
8  B03_fld1:0009-0028:DAPI-0001   54.338   138939.925
9  B03_fld1:0010-0030:DAPI-0001   64.526   360479.676

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld2:0001-0042:DAPI-0001  747.149  9183116.092
1  B03_fld2:0002-0036:DAPI-0001  271.690  2831447.005
2  B03_fld2:0003-0029:DAPI-0001   67.074   311429.370
3  B03_fld2:0004-0038:DAPI-0001  578.191  3198742.714
4  B03_fld2:0005-0031:DAPI-0001  129.902   297916.168
5  B03_fld2:0006-0029:DAPI-0001   92.545   649514.115
6  B03_fld2:0007-0033:DAPI-0001  112.072   613421.743
7  B03_fld2:0008-0037:DAPI-0001  245.370   883856.427
8  B03_fld2:0009-0029:DAPI-0001   44.150   159113.786
9  B03_fld2:0010-0035:DAPI-0001  227.541   577362.483

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld3:0001-0032:DAPI-0001  214.805  1164383.560
1  B03_fld3:0002-0030:DAPI-0001   75.564   212736.982
2  B03_fld3:0003-0031:DAPI-0001  171.505   358284.927
3  B03_fld3:0004-0031:DAPI-0001  185.089   891025.657
4  B03_fld3:0005-0030:DAPI-0001  111.223   543767.965
5  B03_fld3:0006-0031:DAPI-0001  106.978   353521.005
6  B03_fld3:0007-0037:DAPI-0001  167.259   534104.277
7  B03_fld3:0008-0029:DAPI-0001   67.923   228249.655
8  B03_fld3:0009-0040:DAPI-0001  508.570  2500646.110
9  B03_fld3:0010-0041:DAPI-0001  415.177  2978277.838

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld4:0001-0036:DAPI-0001  361.688  1789602.609
1  B03_fld4:0002-0032:DAPI-0001  213.107  1338733.235
2  B03_fld4:0003-0031:DAPI-0001   77.262   323513.649
3  B03_fld4:0004-0026:DAPI-0001   43.301   157811.371
4  B03_fld4:0005-0028:DAPI-0001   53.489    69800.661
5  B03_fld4:0006-0030:DAPI-0001  116.317   576573.732
6  B03_fld4:0007-0031:DAPI-0001  187.636  1064438.849
7  B03_fld4:0008-0030:DAPI-0001  241.974  1255287.773
8  B03_fld4:0009-0034:DAPI-0001  300.558  1767042.967
9  B03_fld4:0010-0030:DAPI-0001   88.299    81228.638

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld5:0001-0026:DAPI-0001  126.506   618399.620
1  B03_fld5:0002-0036:DAPI-0001  453.383  3107143.144
2  B03_fld5:0003-0026:DAPI-0001   56.885   831601.023
3  B03_fld5:0004-0028:DAPI-0001  216.503  3525846.922
4  B03_fld5:0005-0027:DAPI-0001   97.639   498157.089
5  B03_fld5:0006-0029:DAPI-0001  140.939   468805.186
6  B03_fld5:0007-0027:DAPI-0001   68.772   402729.231
7  B03_fld5:0008-0029:DAPI-0001   91.696   401979.536
8  B03_fld5:0009-0035:DAPI-0001  315.840   987051.234
9  B03_fld5:0010-0030:DAPI-0001  141.788   654368.034

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld6:0001-0025:DAPI-0001   46.697   380017.612
1  B03_fld6:0002-0026:DAPI-0001   50.093   303266.771
2  B03_fld6:0003-0028:DAPI-0001  118.865   406637.328
3  B03_fld6:0004-0030:DAPI-0001  146.034   722818.733
4  B03_fld6:0005-0029:DAPI-0001   90.846   260489.966
5  B03_fld6:0006-0027:DAPI-0001   68.772   220832.507
6  B03_fld6:0007-0035:DAPI-0001  472.911  2621184.953
7  B03_fld6:0008-0028:DAPI-0001   84.903   130936.945
8  B03_fld6:0009-0029:DAPI-0001  146.883   497968.604
9  B03_fld6:0010-0035:DAPI-0001  195.277   744808.674

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld7:0001-0034:DAPI-0001  315.840  2267221.602
1  B03_fld7:0002-0038:DAPI-0001  531.494  2670703.076
2  B03_fld7:0003-0029:DAPI-0001   74.715   462421.311
3  B03_fld7:0004-0028:DAPI-0001   51.791   137530.531
4  B03_fld7:0005-0026:DAPI-0001   48.395   360438.073
5  B03_fld7:0006-0028:DAPI-0001   83.205   101562.967
6  B03_fld7:0007-0039:DAPI-0001  469.515  1658678.400
7  B03_fld7:0008-0032:DAPI-0001  193.579   852810.704
8  B03_fld7:0009-0026:DAPI-0001   48.395   150100.457
9  B03_fld7:0010-0031:DAPI-0001  249.616  1630511.747

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B03_fld8:0001-0028:DAPI-0001   78.960   474120.130
1  B03_fld8:0002-0025:DAPI-0001   56.885   603003.265
2  B03_fld8:0003-0027:DAPI-0001   64.526   862942.209
3  B03_fld8:0004-0030:DAPI-0001  123.959   477733.612
4  B03_fld8:0005-0028:DAPI-0001  105.280   397200.332
5  B03_fld8:0006-0031:DAPI-0001  171.505  1124772.797
6  B03_fld8:0007-0030:DAPI-0001  133.298   718424.140
7  B03_fld8:0008-0033:DAPI-0001  305.652   899110.994
8  B03_fld8:0009-0031:DAPI-0001  257.257   973454.827
9  B03_fld8:0010-0027:DAPI-0001   48.395   147826.748

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area      IntDen
0  B03_fld9:0001-0029:DAPI-0001  129.902  689128.274
1  B03_fld9:0002-0029:DAPI-0001  111.223  288912.178
2  B03_fld9:0003-0030:DAPI-0001  138.392  503739.478
3  B03_fld9:0004-0025:DAPI-0001   42.452  197383.078
4  B03_fld9:0005-0033:DAPI-0001  232.635  659882.500
5  B03_fld9:0006-0030:DAPI-0001  160.467  541311.714
6  B03_fld9:0007-0028:DAPI-0001  104.431  237032.047
7  B03_fld9:0008-0030:DAPI-0001   71.319  240232.050
8  B03_fld9:0009-0030:DAPI-0001   68.772  134592.879
9  B03_fld9:0010-0028:DAPI-0001   97.639  292287.083

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld1:0001-0031:DAPI-0001  246.219  2256736.051
1  B04_fld1:0002-0029:DAPI-0001  214.805  1707487.581
2  B04_fld1:0003-0027:DAPI-0001   60.281   123498.571
3  B04_fld1:0004-0026:DAPI-0001   69.621   238892.277
4  B04_fld1:0005-0026:DAPI-0001  114.619   335779.622
5  B04_fld1:0006-0030:DAPI-0001   95.941   134522.409
6  B04_fld1:0007-0030:DAPI-0001  188.485   615378.763
7  B04_fld1:0008-0025:DAPI-0001   51.791   133431.402
8  B04_fld1:0009-0026:DAPI-0001   94.243   184319.015
9  B04_fld1:0010-0028:DAPI-0001   91.696   304604.846

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld2:0001-0024:DAPI-0001   49.244   135048.809
1  B04_fld2:0002-0027:DAPI-0001  106.978   741093.308
2  B04_fld2:0003-0037:DAPI-0001  522.155  1600144.401
3  B04_fld2:0004-0028:DAPI-0001  101.884   297647.874
4  B04_fld2:0005-0026:DAPI-0001   69.621   250715.055
5  B04_fld2:0006-0028:DAPI-0001   91.696   138115.514
6  B04_fld2:0007-0025:DAPI-0001   57.734   139807.636
7  B04_fld2:0008-0032:DAPI-0001  251.314  1261045.062
8  B04_fld2:0009-0030:DAPI-0001  196.976   865311.009
9  B04_fld2:0010-0026:DAPI-0001  112.921   574643.032

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld3:0001-0035:DAPI-0001  625.737  4305663.754
1  B04_fld3:0002-0037:DAPI-0001  474.609  2850374.487
2  B04_fld3:0003-0033:DAPI-0001  278.483  1426431.501
3  B04_fld3:0004-0028:DAPI-0001  105.280   599483.176
4  B04_fld3:0005-0032:DAPI-0001  392.253  1971437.355
5  B04_fld3:0006-0024:DAPI-0001   49.244   228245.409
6  B04_fld3:0007-0026:DAPI-0001  141.788   804625.562
7  B04_fld3:0008-0033:DAPI-0001  314.991   906127.398
8  B04_fld3:0009-0035:DAPI-0001  300.558   979246.078
9  B04_fld3:0010-0029:DAPI-0001  196.976   812112.331

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld4:0001-0030:DAPI-0001   94.243   547996.996
1  B04_fld4:0002-0032:DAPI-0001  181.693  1044757.426
2  B04_fld4:0003-0032:DAPI-0001   80.658   290005.732
3  B04_fld4:0004-0032:DAPI-0001  114.619   249282.737
4  B04_fld4:0005-0041:DAPI-0001  587.530  1838257.266
5  B04_fld4:0006-0030:DAPI-0001   53.489   154027.233
6  B04_fld4:0007-0032:DAPI-0001   60.281   159028.883
7  B04_fld4:0008-0034:DAPI-0001   93.394   199911.497
8  B04_fld4:0009-0047:DAPI-0001  298.010  1406621.025
9  B04_fld4:0010-0046:DAPI-0001  150.279   826503.432

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld5:0001-0033:DAPI-0001  280.181  2177985.738
1  B04_fld5:0002-0054:DAPI-0001  707.244  7883798.342
2  B04_fld5:0003-0057:DAPI-0001   88.299  1021431.107
3  B04_fld5:0004-0069:DAPI-0001  355.745  5107006.107
4  B04_fld5:0005-0090:DAPI-0001  800.638  4852372.767
5  B04_fld5:0006-0095:DAPI-0001  545.079  4065684.715
6  B04_fld5:0007-0093:DAPI-0001  101.884   694147.754
7  B04_fld5:0008-0092:DAPI-0001  111.223   836729.179
8  B04_fld5:0009-0097:DAPI-0001  173.203  1191855.705
9  B04_fld5:0010-0101:DAPI-0001  368.480  2049122.980

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld6:0001-0034:DAPI-0001  160.467   969956.813
1  B04_fld6:0002-0032:DAPI-0001  104.431   389688.092
2  B04_fld6:0003-0033:DAPI-0001   96.790   453253.458
3  B04_fld6:0004-0042:DAPI-0001  514.514  2174766.207
4  B04_fld6:0005-0035:DAPI-0001  137.543   816034.012
5  B04_fld6:0006-0038:DAPI-0001  511.118  3354200.566
6  B04_fld6:0007-0034:DAPI-0001  130.751   517194.945
7  B04_fld6:0008-0037:DAPI-0001  219.899  1249278.320
8  B04_fld6:0009-0040:DAPI-0001  225.843   768325.177
9  B04_fld6:0010-0041:DAPI-0001  140.090  1067919.882

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area      IntDen
0  B04_fld7:0001-0029:DAPI-0001  112.072  854217.551
1  B04_fld7:0002-0028:DAPI-0001   43.301  250105.449
2  B04_fld7:0003-0029:DAPI-0001   71.319  344417.679
3  B04_fld7:0004-0029:DAPI-0001   95.941  221577.957
4  B04_fld7:0005-0029:DAPI-0001   57.734  136234.058
5  B04_fld7:0006-0029:DAPI-0001   83.205  394801.815
6  B04_fld7:0007-0029:DAPI-0001   59.432  185252.101
7  B04_fld7:0008-0032:DAPI-0001  129.053  372726.970
8  B04_fld7:0009-0030:DAPI-0001  127.355  900304.733
9  B04_fld7:0010-0033:DAPI-0001  116.317  382993.471

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld8:0001-0040:DAPI-0001  802.336  6528315.394
1  B04_fld8:0002-0035:DAPI-0001  338.764  1135887.482
2  B04_fld8:0003-0030:DAPI-0001  106.129   671538.018
3  B04_fld8:0004-0028:DAPI-0001   42.452   119476.704
4  B04_fld8:0005-0034:DAPI-0001  200.372   809274.864
5  B04_fld8:0006-0033:DAPI-0001  285.275   952976.163
6  B04_fld8:0007-0036:DAPI-0001  179.995   873333.518
7  B04_fld8:0008-0028:DAPI-0001   66.225   259992.433
8  B04_fld8:0009-0030:DAPI-0001   77.262   433817.406
9  B04_fld8:0010-0040:DAPI-0001  169.807   552801.671

 * * * * * * * * * * * * * * * * * * * * * * * * * *

                          Label     Area       IntDen
0  B04_fld9:0001-0039:DAPI-0001  310.746  1075427.877
1  B04_fld9:0002-0033:DAPI-0001  185.089   902449.390
2  B04_fld9:0003-0036:DAPI-0001  259.804  2950736.073
3  B04_fld9:0004-0034:DAPI-0001  172.354   947401.416
4  B04_fld9:0005-0039:DAPI-0001  230.088   790862.745
5  B04_fld9:0006-0048:DAPI-0001  552.720  1895669.694
6  B04_fld9:0007-0028:DAPI-0001   43.301    40896.198
7  B04_fld9:0008-0036:DAPI-0001  218.201  1285151.642
8  B04_fld9:0009-0036:DAPI-0001  106.978   227376.849
9  B04_fld9:0010-0036:DAPI-0001  114.619   459331.682

In [3]:
for df in df_Nuc:
    print('\n', '* ' * 26, '\n')
    print(df.info())

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22776 entries, 0 to 22775
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   22776 non-null  object
 1   Area    22776 non-null  float64
 2   IntDen  22776 non-null  float64
dtypes: float64(2), object(1)
memory usage: 533.9+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8424 entries, 0 to 8423
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   8424 non-null   object
 1   Area    8424 non-null   float64
 2   IntDen  8424 non-null   float64
dtypes: float64(2), object(1)
memory usage: 197.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20664 entries, 0 to 20663
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   20664 non-null  object
 1   Area    20664 non-null  float64
 2   IntDen  20664 non-null  float64
dtypes: float64(2), object(1)
memory usage: 484.4+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18432 entries, 0 to 18431
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   18432 non-null  object
 1   Area    18432 non-null  float64
 2   IntDen  18432 non-null  float64
dtypes: float64(2), object(1)
memory usage: 432.1+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8400 entries, 0 to 8399
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   8400 non-null   object
 1   Area    8400 non-null   float64
 2   IntDen  8400 non-null   float64
dtypes: float64(2), object(1)
memory usage: 197.0+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12240 entries, 0 to 12239
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   12240 non-null  object
 1   Area    12240 non-null  float64
 2   IntDen  12240 non-null  float64
dtypes: float64(2), object(1)
memory usage: 287.0+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20040 entries, 0 to 20039
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   20040 non-null  object
 1   Area    20040 non-null  float64
 2   IntDen  20040 non-null  float64
dtypes: float64(2), object(1)
memory usage: 469.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17568 entries, 0 to 17567
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   17568 non-null  object
 1   Area    17568 non-null  float64
 2   IntDen  17568 non-null  float64
dtypes: float64(2), object(1)
memory usage: 411.9+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16320 entries, 0 to 16319
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   16320 non-null  object
 1   Area    16320 non-null  float64
 2   IntDen  16320 non-null  float64
dtypes: float64(2), object(1)
memory usage: 382.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15720 entries, 0 to 15719
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   15720 non-null  object
 1   Area    15720 non-null  float64
 2   IntDen  15720 non-null  float64
dtypes: float64(2), object(1)
memory usage: 368.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12768 entries, 0 to 12767
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   12768 non-null  object
 1   Area    12768 non-null  float64
 2   IntDen  12768 non-null  float64
dtypes: float64(2), object(1)
memory usage: 299.4+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14232 entries, 0 to 14231
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   14232 non-null  object
 1   Area    14232 non-null  float64
 2   IntDen  14232 non-null  float64
dtypes: float64(2), object(1)
memory usage: 333.7+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13104 entries, 0 to 13103
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   13104 non-null  object
 1   Area    13104 non-null  float64
 2   IntDen  13104 non-null  float64
dtypes: float64(2), object(1)
memory usage: 307.2+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10248 entries, 0 to 10247
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   10248 non-null  object
 1   Area    10248 non-null  float64
 2   IntDen  10248 non-null  float64
dtypes: float64(2), object(1)
memory usage: 240.3+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17400 entries, 0 to 17399
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   17400 non-null  object
 1   Area    17400 non-null  float64
 2   IntDen  17400 non-null  float64
dtypes: float64(2), object(1)
memory usage: 407.9+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13416 entries, 0 to 13415
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   13416 non-null  object
 1   Area    13416 non-null  float64
 2   IntDen  13416 non-null  float64
dtypes: float64(2), object(1)
memory usage: 314.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16872 entries, 0 to 16871
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   16872 non-null  object
 1   Area    16872 non-null  float64
 2   IntDen  16872 non-null  float64
dtypes: float64(2), object(1)
memory usage: 395.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24216 entries, 0 to 24215
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   24216 non-null  object
 1   Area    24216 non-null  float64
 2   IntDen  24216 non-null  float64
dtypes: float64(2), object(1)
memory usage: 567.7+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16584 entries, 0 to 16583
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   16584 non-null  object
 1   Area    16584 non-null  float64
 2   IntDen  16584 non-null  float64
dtypes: float64(2), object(1)
memory usage: 388.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6264 entries, 0 to 6263
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   6264 non-null   object
 1   Area    6264 non-null   float64
 2   IntDen  6264 non-null   float64
dtypes: float64(2), object(1)
memory usage: 146.9+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14928 entries, 0 to 14927
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   14928 non-null  object
 1   Area    14928 non-null  float64
 2   IntDen  14928 non-null  float64
dtypes: float64(2), object(1)
memory usage: 350.0+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11592 entries, 0 to 11591
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   11592 non-null  object
 1   Area    11592 non-null  float64
 2   IntDen  11592 non-null  float64
dtypes: float64(2), object(1)
memory usage: 271.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5448 entries, 0 to 5447
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   5448 non-null   object
 1   Area    5448 non-null   float64
 2   IntDen  5448 non-null   float64
dtypes: float64(2), object(1)
memory usage: 127.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10128 entries, 0 to 10127
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   10128 non-null  object
 1   Area    10128 non-null  float64
 2   IntDen  10128 non-null  float64
dtypes: float64(2), object(1)
memory usage: 237.5+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16704 entries, 0 to 16703
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   16704 non-null  object
 1   Area    16704 non-null  float64
 2   IntDen  16704 non-null  float64
dtypes: float64(2), object(1)
memory usage: 391.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19176 entries, 0 to 19175
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   19176 non-null  object
 1   Area    19176 non-null  float64
 2   IntDen  19176 non-null  float64
dtypes: float64(2), object(1)
memory usage: 449.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16224 entries, 0 to 16223
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   16224 non-null  object
 1   Area    16224 non-null  float64
 2   IntDen  16224 non-null  float64
dtypes: float64(2), object(1)
memory usage: 380.4+ KB
None

In [4]:
well = r'[A-Z]+.*?(?=_)'
field = r'(?<=d)[\d]{1,1}?(?=:)'
cell_id = r'(\d+)-(\d+)'
channel = r'(?<=:)[A-Z]+.*?(?=-)'

for k in range(len(df_Nuc)):
    df_Nuc[k]['Well'] = df_Nuc[k]['Label'].apply(lambda x: re.search(well, x).group())
    df_Nuc[k]['Field'] = df_Nuc[k]['Label'].apply(lambda x: re.search(field, x).group())
    df_Nuc[k]['Cell ID'] = df_Nuc[k]['Label'].apply(lambda x: re.search(cell_id, x).group())
    df_Nuc[k]['Channel'] = df_Nuc[k]['Label'].apply(lambda x: re.search(channel, x).group())
    df_Nuc[k]['Cycle'] = df_Nuc[k]['Label'].apply(lambda x: int(x[-1]))
    df_Nuc[k] = df_Nuc[k][['Cell ID', 'Well', 'Field', 'Channel', 'Cycle', 'Area', 'IntDen']]

In [5]:
for df in df_Nuc:
    print('\n', '* ' * 32, '\n')
    print(df.head(10))

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0031  B02     1    DAPI      1  166.410   450411.746
1  0002-0033  B02     1    DAPI      1   92.545   250158.089
2  0003-0032  B02     1    DAPI      1  145.185   470850.506
3  0004-0029  B02     1    DAPI      1   82.356   171596.262
4  0005-0033  B02     1    DAPI      1  273.388  1090953.285
5  0006-0030  B02     1    DAPI      1   73.017   195095.784
6  0007-0031  B02     1    DAPI      1  118.865   535500.086
7  0008-0033  B02     1    DAPI      1  238.578  1154179.887
8  0009-0034  B02     1    DAPI      1  320.934  1048435.435
9  0010-0031  B02     1    DAPI      1  142.637   731758.196

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0027  B02     2    DAPI      1  108.676  1244034.696
1  0002-0028  B02     2    DAPI      1   54.338   240530.910
2  0003-0031  B02     2    DAPI      1   93.394   391233.331
3  0004-0034  B02     2    DAPI      1  257.257   937947.439
4  0005-0031  B02     2    DAPI      1   95.941   157731.561
5  0006-0036  B02     2    DAPI      1  142.637   704576.420
6  0007-0041  B02     2    DAPI      1  219.899  1498138.239
7  0008-0035  B02     2    DAPI      1  119.714   493348.169
8  0009-0039  B02     2    DAPI      1  119.714   372769.421
9  0010-0038  B02     2    DAPI      1  103.582   254687.678

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0027  B02     3    DAPI      1   43.301   288791.616
1  0002-0032  B02     3    DAPI      1  164.712  1328104.197
2  0003-0036  B02     3    DAPI      1  190.183  1057935.260
3  0004-0031  B02     3    DAPI      1   89.148   313979.014
4  0005-0031  B02     3    DAPI      1  105.280   495186.325
5  0006-0034  B02     3    DAPI      1  116.317   472214.901
6  0007-0030  B02     3    DAPI      1   77.262   184250.243
7  0008-0037  B02     3    DAPI      1  163.014   826505.130
8  0009-0033  B02     3    DAPI      1  135.845   478079.169
9  0010-0031  B02     3    DAPI      1   46.697   136228.115

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0034  B02     4    DAPI      1  268.294  1395258.423
1  0002-0031  B02     4    DAPI      1  361.688  2266032.108
2  0003-0029  B02     4    DAPI      1   76.413   216584.797
3  0004-0033  B02     4    DAPI      1  172.354  1065205.525
4  0005-0030  B02     4    DAPI      1   95.941   400430.051
5  0006-0037  B02     4    DAPI      1  204.617   433561.847
6  0007-0034  B02     4    DAPI      1  222.447   532668.563
7  0008-0035  B02     4    DAPI      1  203.768   503988.245
8  0009-0028  B02     4    DAPI      1   50.093   106361.699
9  0010-0030  B02     4    DAPI      1   65.376   160938.357

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0030  B02     5    DAPI      1  176.599   561961.033
1  0002-0028  B02     5    DAPI      1   89.997   399827.238
2  0003-0041  B02     5    DAPI      1  456.779  3250350.306
3  0004-0030  B02     5    DAPI      1  173.203  1380659.309
4  0005-0029  B02     5    DAPI      1   56.036   197871.271
5  0006-0041  B02     5    DAPI      1  455.081  3416747.093
6  0007-0037  B02     5    DAPI      1  301.407  2304663.936
7  0008-0043  B02     5    DAPI      1  218.201  1164959.204
8  0009-0043  B02     5    DAPI      1  132.449  1033523.877
9  0010-0052  B02     5    DAPI      1  303.105  1180324.994

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0035  B02     6    DAPI      1  412.630  2740816.181
1  0002-0031  B02     6    DAPI      1  234.333   980918.672
2  0003-0042  B02     6    DAPI      1  620.643  3750803.179
3  0004-0030  B02     6    DAPI      1  178.297  1123081.524
4  0005-0029  B02     6    DAPI      1   96.790   489284.700
5  0006-0029  B02     6    DAPI      1   84.903   281155.417
6  0007-0035  B02     6    DAPI      1  210.560  1532201.424
7  0008-0033  B02     6    DAPI      1  121.412   528801.220
8  0009-0033  B02     6    DAPI      1  149.430  2607186.105
9  0010-0034  B02     6    DAPI      1  109.525   691347.644

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0030  B02     7    DAPI      1  376.970  1553363.559
1  0002-0036  B02     7    DAPI      1  325.179  4507605.287
2  0003-0028  B02     7    DAPI      1   66.225   154967.112
3  0004-0026  B02     7    DAPI      1   52.640   171081.749
4  0005-0027  B02     7    DAPI      1  108.676   619858.258
5  0006-0031  B02     7    DAPI      1  157.920   815239.317
6  0007-0029  B02     7    DAPI      1   94.243   443255.251
7  0008-0026  B02     7    DAPI      1   85.752   447468.150
8  0009-0029  B02     7    DAPI      1   72.168   154517.973
9  0010-0026  B02     7    DAPI      1   68.772   356582.616

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0027  B02     8    DAPI      1   92.545  1126441.995
1  0002-0032  B02     8    DAPI      1  367.631  2395408.530
2  0003-0028  B02     8    DAPI      1  145.185  1680668.342
3  0004-0024  B02     8    DAPI      1   53.489   264038.922
4  0005-0025  B02     8    DAPI      1   42.452   130905.530
5  0006-0030  B02     8    DAPI      1  169.807   985452.506
6  0007-0030  B02     8    DAPI      1  199.523   856241.644
7  0008-0027  B02     8    DAPI      1   94.243   645608.565
8  0009-0029  B02     8    DAPI      1  149.430   965544.391
9  0010-0026  B02     8    DAPI      1   85.752   370769.950

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0032  B02     9    DAPI      1  292.916  1341812.676
1  0002-0028  B02     9    DAPI      1  122.261   599526.477
2  0003-0031  B02     9    DAPI      1  193.579  1002047.695
3  0004-0027  B02     9    DAPI      1  139.241  1125300.046
4  0005-0029  B02     9    DAPI      1   79.809   548677.071
5  0006-0034  B02     9    DAPI      1  134.147   491625.482
6  0007-0038  B02     9    DAPI      1  349.801  2168608.174
7  0008-0041  B02     9    DAPI      1  300.558  2438736.357
8  0009-0037  B02     9    DAPI      1  140.090   102060.500
9  0010-0040  B02     9    DAPI      1   79.809   648137.833

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0039  B03     1    DAPI      1  324.330   792661.845
1  0002-0032  B03     1    DAPI      1  157.920   602391.112
2  0003-0034  B03     1    DAPI      1  179.146   819851.262
3  0004-0029  B03     1    DAPI      1   67.074   211967.758
4  0005-0036  B03     1    DAPI      1  253.012  1150742.155
5  0006-0032  B03     1    DAPI      1  187.636   516182.898
6  0007-0032  B03     1    DAPI      1   86.601   192612.364
7  0008-0036  B03     1    DAPI      1  347.254   948836.281
8  0009-0028  B03     1    DAPI      1   54.338   138939.925
9  0010-0030  B03     1    DAPI      1   64.526   360479.676

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0042  B03     2    DAPI      1  747.149  9183116.092
1  0002-0036  B03     2    DAPI      1  271.690  2831447.005
2  0003-0029  B03     2    DAPI      1   67.074   311429.370
3  0004-0038  B03     2    DAPI      1  578.191  3198742.714
4  0005-0031  B03     2    DAPI      1  129.902   297916.168
5  0006-0029  B03     2    DAPI      1   92.545   649514.115
6  0007-0033  B03     2    DAPI      1  112.072   613421.743
7  0008-0037  B03     2    DAPI      1  245.370   883856.427
8  0009-0029  B03     2    DAPI      1   44.150   159113.786
9  0010-0035  B03     2    DAPI      1  227.541   577362.483

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0032  B03     3    DAPI      1  214.805  1164383.560
1  0002-0030  B03     3    DAPI      1   75.564   212736.982
2  0003-0031  B03     3    DAPI      1  171.505   358284.927
3  0004-0031  B03     3    DAPI      1  185.089   891025.657
4  0005-0030  B03     3    DAPI      1  111.223   543767.965
5  0006-0031  B03     3    DAPI      1  106.978   353521.005
6  0007-0037  B03     3    DAPI      1  167.259   534104.277
7  0008-0029  B03     3    DAPI      1   67.923   228249.655
8  0009-0040  B03     3    DAPI      1  508.570  2500646.110
9  0010-0041  B03     3    DAPI      1  415.177  2978277.838

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0036  B03     4    DAPI      1  361.688  1789602.609
1  0002-0032  B03     4    DAPI      1  213.107  1338733.235
2  0003-0031  B03     4    DAPI      1   77.262   323513.649
3  0004-0026  B03     4    DAPI      1   43.301   157811.371
4  0005-0028  B03     4    DAPI      1   53.489    69800.661
5  0006-0030  B03     4    DAPI      1  116.317   576573.732
6  0007-0031  B03     4    DAPI      1  187.636  1064438.849
7  0008-0030  B03     4    DAPI      1  241.974  1255287.773
8  0009-0034  B03     4    DAPI      1  300.558  1767042.967
9  0010-0030  B03     4    DAPI      1   88.299    81228.638

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0026  B03     5    DAPI      1  126.506   618399.620
1  0002-0036  B03     5    DAPI      1  453.383  3107143.144
2  0003-0026  B03     5    DAPI      1   56.885   831601.023
3  0004-0028  B03     5    DAPI      1  216.503  3525846.922
4  0005-0027  B03     5    DAPI      1   97.639   498157.089
5  0006-0029  B03     5    DAPI      1  140.939   468805.186
6  0007-0027  B03     5    DAPI      1   68.772   402729.231
7  0008-0029  B03     5    DAPI      1   91.696   401979.536
8  0009-0035  B03     5    DAPI      1  315.840   987051.234
9  0010-0030  B03     5    DAPI      1  141.788   654368.034

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0025  B03     6    DAPI      1   46.697   380017.612
1  0002-0026  B03     6    DAPI      1   50.093   303266.771
2  0003-0028  B03     6    DAPI      1  118.865   406637.328
3  0004-0030  B03     6    DAPI      1  146.034   722818.733
4  0005-0029  B03     6    DAPI      1   90.846   260489.966
5  0006-0027  B03     6    DAPI      1   68.772   220832.507
6  0007-0035  B03     6    DAPI      1  472.911  2621184.953
7  0008-0028  B03     6    DAPI      1   84.903   130936.945
8  0009-0029  B03     6    DAPI      1  146.883   497968.604
9  0010-0035  B03     6    DAPI      1  195.277   744808.674

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0034  B03     7    DAPI      1  315.840  2267221.602
1  0002-0038  B03     7    DAPI      1  531.494  2670703.076
2  0003-0029  B03     7    DAPI      1   74.715   462421.311
3  0004-0028  B03     7    DAPI      1   51.791   137530.531
4  0005-0026  B03     7    DAPI      1   48.395   360438.073
5  0006-0028  B03     7    DAPI      1   83.205   101562.967
6  0007-0039  B03     7    DAPI      1  469.515  1658678.400
7  0008-0032  B03     7    DAPI      1  193.579   852810.704
8  0009-0026  B03     7    DAPI      1   48.395   150100.457
9  0010-0031  B03     7    DAPI      1  249.616  1630511.747

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0028  B03     8    DAPI      1   78.960   474120.130
1  0002-0025  B03     8    DAPI      1   56.885   603003.265
2  0003-0027  B03     8    DAPI      1   64.526   862942.209
3  0004-0030  B03     8    DAPI      1  123.959   477733.612
4  0005-0028  B03     8    DAPI      1  105.280   397200.332
5  0006-0031  B03     8    DAPI      1  171.505  1124772.797
6  0007-0030  B03     8    DAPI      1  133.298   718424.140
7  0008-0033  B03     8    DAPI      1  305.652   899110.994
8  0009-0031  B03     8    DAPI      1  257.257   973454.827
9  0010-0027  B03     8    DAPI      1   48.395   147826.748

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area      IntDen
0  0001-0029  B03     9    DAPI      1  129.902  689128.274
1  0002-0029  B03     9    DAPI      1  111.223  288912.178
2  0003-0030  B03     9    DAPI      1  138.392  503739.478
3  0004-0025  B03     9    DAPI      1   42.452  197383.078
4  0005-0033  B03     9    DAPI      1  232.635  659882.500
5  0006-0030  B03     9    DAPI      1  160.467  541311.714
6  0007-0028  B03     9    DAPI      1  104.431  237032.047
7  0008-0030  B03     9    DAPI      1   71.319  240232.050
8  0009-0030  B03     9    DAPI      1   68.772  134592.879
9  0010-0028  B03     9    DAPI      1   97.639  292287.083

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0031  B04     1    DAPI      1  246.219  2256736.051
1  0002-0029  B04     1    DAPI      1  214.805  1707487.581
2  0003-0027  B04     1    DAPI      1   60.281   123498.571
3  0004-0026  B04     1    DAPI      1   69.621   238892.277
4  0005-0026  B04     1    DAPI      1  114.619   335779.622
5  0006-0030  B04     1    DAPI      1   95.941   134522.409
6  0007-0030  B04     1    DAPI      1  188.485   615378.763
7  0008-0025  B04     1    DAPI      1   51.791   133431.402
8  0009-0026  B04     1    DAPI      1   94.243   184319.015
9  0010-0028  B04     1    DAPI      1   91.696   304604.846

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0024  B04     2    DAPI      1   49.244   135048.809
1  0002-0027  B04     2    DAPI      1  106.978   741093.308
2  0003-0037  B04     2    DAPI      1  522.155  1600144.401
3  0004-0028  B04     2    DAPI      1  101.884   297647.874
4  0005-0026  B04     2    DAPI      1   69.621   250715.055
5  0006-0028  B04     2    DAPI      1   91.696   138115.514
6  0007-0025  B04     2    DAPI      1   57.734   139807.636
7  0008-0032  B04     2    DAPI      1  251.314  1261045.062
8  0009-0030  B04     2    DAPI      1  196.976   865311.009
9  0010-0026  B04     2    DAPI      1  112.921   574643.032

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0035  B04     3    DAPI      1  625.737  4305663.754
1  0002-0037  B04     3    DAPI      1  474.609  2850374.487
2  0003-0033  B04     3    DAPI      1  278.483  1426431.501
3  0004-0028  B04     3    DAPI      1  105.280   599483.176
4  0005-0032  B04     3    DAPI      1  392.253  1971437.355
5  0006-0024  B04     3    DAPI      1   49.244   228245.409
6  0007-0026  B04     3    DAPI      1  141.788   804625.562
7  0008-0033  B04     3    DAPI      1  314.991   906127.398
8  0009-0035  B04     3    DAPI      1  300.558   979246.078
9  0010-0029  B04     3    DAPI      1  196.976   812112.331

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0030  B04     4    DAPI      1   94.243   547996.996
1  0002-0032  B04     4    DAPI      1  181.693  1044757.426
2  0003-0032  B04     4    DAPI      1   80.658   290005.732
3  0004-0032  B04     4    DAPI      1  114.619   249282.737
4  0005-0041  B04     4    DAPI      1  587.530  1838257.266
5  0006-0030  B04     4    DAPI      1   53.489   154027.233
6  0007-0032  B04     4    DAPI      1   60.281   159028.883
7  0008-0034  B04     4    DAPI      1   93.394   199911.497
8  0009-0047  B04     4    DAPI      1  298.010  1406621.025
9  0010-0046  B04     4    DAPI      1  150.279   826503.432

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0033  B04     5    DAPI      1  280.181  2177985.738
1  0002-0054  B04     5    DAPI      1  707.244  7883798.342
2  0003-0057  B04     5    DAPI      1   88.299  1021431.107
3  0004-0069  B04     5    DAPI      1  355.745  5107006.107
4  0005-0090  B04     5    DAPI      1  800.638  4852372.767
5  0006-0095  B04     5    DAPI      1  545.079  4065684.715
6  0007-0093  B04     5    DAPI      1  101.884   694147.754
7  0008-0092  B04     5    DAPI      1  111.223   836729.179
8  0009-0097  B04     5    DAPI      1  173.203  1191855.705
9  0010-0101  B04     5    DAPI      1  368.480  2049122.980

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0034  B04     6    DAPI      1  160.467   969956.813
1  0002-0032  B04     6    DAPI      1  104.431   389688.092
2  0003-0033  B04     6    DAPI      1   96.790   453253.458
3  0004-0042  B04     6    DAPI      1  514.514  2174766.207
4  0005-0035  B04     6    DAPI      1  137.543   816034.012
5  0006-0038  B04     6    DAPI      1  511.118  3354200.566
6  0007-0034  B04     6    DAPI      1  130.751   517194.945
7  0008-0037  B04     6    DAPI      1  219.899  1249278.320
8  0009-0040  B04     6    DAPI      1  225.843   768325.177
9  0010-0041  B04     6    DAPI      1  140.090  1067919.882

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area      IntDen
0  0001-0029  B04     7    DAPI      1  112.072  854217.551
1  0002-0028  B04     7    DAPI      1   43.301  250105.449
2  0003-0029  B04     7    DAPI      1   71.319  344417.679
3  0004-0029  B04     7    DAPI      1   95.941  221577.957
4  0005-0029  B04     7    DAPI      1   57.734  136234.058
5  0006-0029  B04     7    DAPI      1   83.205  394801.815
6  0007-0029  B04     7    DAPI      1   59.432  185252.101
7  0008-0032  B04     7    DAPI      1  129.053  372726.970
8  0009-0030  B04     7    DAPI      1  127.355  900304.733
9  0010-0033  B04     7    DAPI      1  116.317  382993.471

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0040  B04     8    DAPI      1  802.336  6528315.394
1  0002-0035  B04     8    DAPI      1  338.764  1135887.482
2  0003-0030  B04     8    DAPI      1  106.129   671538.018
3  0004-0028  B04     8    DAPI      1   42.452   119476.704
4  0005-0034  B04     8    DAPI      1  200.372   809274.864
5  0006-0033  B04     8    DAPI      1  285.275   952976.163
6  0007-0036  B04     8    DAPI      1  179.995   873333.518
7  0008-0028  B04     8    DAPI      1   66.225   259992.433
8  0009-0030  B04     8    DAPI      1   77.262   433817.406
9  0010-0040  B04     8    DAPI      1  169.807   552801.671

 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

     Cell ID Well Field Channel  Cycle     Area       IntDen
0  0001-0039  B04     9    DAPI      1  310.746  1075427.877
1  0002-0033  B04     9    DAPI      1  185.089   902449.390
2  0003-0036  B04     9    DAPI      1  259.804  2950736.073
3  0004-0034  B04     9    DAPI      1  172.354   947401.416
4  0005-0039  B04     9    DAPI      1  230.088   790862.745
5  0006-0048  B04     9    DAPI      1  552.720  1895669.694
6  0007-0028  B04     9    DAPI      1   43.301    40896.198
7  0008-0036  B04     9    DAPI      1  218.201  1285151.642
8  0009-0036  B04     9    DAPI      1  106.978   227376.849
9  0010-0036  B04     9    DAPI      1  114.619   459331.682

In [6]:
for df in df_Nuc[:n]:
    print('\n', '* ' * 26, '\n')
    print(df.info())

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22776 entries, 0 to 22775
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  22776 non-null  object
 1   Well     22776 non-null  object
 2   Field    22776 non-null  object
 3   Channel  22776 non-null  object
 4   Cycle    22776 non-null  int64
 5   Area     22776 non-null  float64
 6   IntDen   22776 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ MB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8424 entries, 0 to 8423
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  8424 non-null   object
 1   Well     8424 non-null   object
 2   Field    8424 non-null   object
 3   Channel  8424 non-null   object
 4   Cycle    8424 non-null   int64
 5   Area     8424 non-null   float64
 6   IntDen   8424 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 460.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20664 entries, 0 to 20663
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  20664 non-null  object
 1   Well     20664 non-null  object
 2   Field    20664 non-null  object
 3   Channel  20664 non-null  object
 4   Cycle    20664 non-null  int64
 5   Area     20664 non-null  float64
 6   IntDen   20664 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.1+ MB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18432 entries, 0 to 18431
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  18432 non-null  object
 1   Well     18432 non-null  object
 2   Field    18432 non-null  object
 3   Channel  18432 non-null  object
 4   Cycle    18432 non-null  int64
 5   Area     18432 non-null  float64
 6   IntDen   18432 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1008.1+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8400 entries, 0 to 8399
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  8400 non-null   object
 1   Well     8400 non-null   object
 2   Field    8400 non-null   object
 3   Channel  8400 non-null   object
 4   Cycle    8400 non-null   int64
 5   Area     8400 non-null   float64
 6   IntDen   8400 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 459.5+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12240 entries, 0 to 12239
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  12240 non-null  object
 1   Well     12240 non-null  object
 2   Field    12240 non-null  object
 3   Channel  12240 non-null  object
 4   Cycle    12240 non-null  int64
 5   Area     12240 non-null  float64
 6   IntDen   12240 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 669.5+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20040 entries, 0 to 20039
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  20040 non-null  object
 1   Well     20040 non-null  object
 2   Field    20040 non-null  object
 3   Channel  20040 non-null  object
 4   Cycle    20040 non-null  int64
 5   Area     20040 non-null  float64
 6   IntDen   20040 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.1+ MB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17568 entries, 0 to 17567
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  17568 non-null  object
 1   Well     17568 non-null  object
 2   Field    17568 non-null  object
 3   Channel  17568 non-null  object
 4   Cycle    17568 non-null  int64
 5   Area     17568 non-null  float64
 6   IntDen   17568 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 960.9+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16320 entries, 0 to 16319
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  16320 non-null  object
 1   Well     16320 non-null  object
 2   Field    16320 non-null  object
 3   Channel  16320 non-null  object
 4   Cycle    16320 non-null  int64
 5   Area     16320 non-null  float64
 6   IntDen   16320 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 892.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15720 entries, 0 to 15719
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  15720 non-null  object
 1   Well     15720 non-null  object
 2   Field    15720 non-null  object
 3   Channel  15720 non-null  object
 4   Cycle    15720 non-null  int64
 5   Area     15720 non-null  float64
 6   IntDen   15720 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 859.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12768 entries, 0 to 12767
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  12768 non-null  object
 1   Well     12768 non-null  object
 2   Field    12768 non-null  object
 3   Channel  12768 non-null  object
 4   Cycle    12768 non-null  int64
 5   Area     12768 non-null  float64
 6   IntDen   12768 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 698.4+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14232 entries, 0 to 14231
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  14232 non-null  object
 1   Well     14232 non-null  object
 2   Field    14232 non-null  object
 3   Channel  14232 non-null  object
 4   Cycle    14232 non-null  int64
 5   Area     14232 non-null  float64
 6   IntDen   14232 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 778.4+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13104 entries, 0 to 13103
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  13104 non-null  object
 1   Well     13104 non-null  object
 2   Field    13104 non-null  object
 3   Channel  13104 non-null  object
 4   Cycle    13104 non-null  int64
 5   Area     13104 non-null  float64
 6   IntDen   13104 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 716.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10248 entries, 0 to 10247
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  10248 non-null  object
 1   Well     10248 non-null  object
 2   Field    10248 non-null  object
 3   Channel  10248 non-null  object
 4   Cycle    10248 non-null  int64
 5   Area     10248 non-null  float64
 6   IntDen   10248 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 560.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17400 entries, 0 to 17399
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  17400 non-null  object
 1   Well     17400 non-null  object
 2   Field    17400 non-null  object
 3   Channel  17400 non-null  object
 4   Cycle    17400 non-null  int64
 5   Area     17400 non-null  float64
 6   IntDen   17400 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 951.7+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13416 entries, 0 to 13415
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  13416 non-null  object
 1   Well     13416 non-null  object
 2   Field    13416 non-null  object
 3   Channel  13416 non-null  object
 4   Cycle    13416 non-null  int64
 5   Area     13416 non-null  float64
 6   IntDen   13416 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 733.8+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16872 entries, 0 to 16871
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  16872 non-null  object
 1   Well     16872 non-null  object
 2   Field    16872 non-null  object
 3   Channel  16872 non-null  object
 4   Cycle    16872 non-null  int64
 5   Area     16872 non-null  float64
 6   IntDen   16872 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 922.8+ KB

None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24216 entries, 0 to 24215
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  24216 non-null  object
 1   Well     24216 non-null  object
 2   Field    24216 non-null  object
 3   Channel  24216 non-null  object
 4   Cycle    24216 non-null  int64
 5   Area     24216 non-null  float64
 6   IntDen   24216 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.3+ MB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16584 entries, 0 to 16583
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  16584 non-null  object
 1   Well     16584 non-null  object
 2   Field    16584 non-null  object
 3   Channel  16584 non-null  object
 4   Cycle    16584 non-null  int64
 5   Area     16584 non-null  float64
 6   IntDen   16584 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 907.1+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6264 entries, 0 to 6263
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  6264 non-null   object
 1   Well     6264 non-null   object
 2   Field    6264 non-null   object
 3   Channel  6264 non-null   object
 4   Cycle    6264 non-null   int64
 5   Area     6264 non-null   float64
 6   IntDen   6264 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 342.7+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14928 entries, 0 to 14927
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  14928 non-null  object
 1   Well     14928 non-null  object
 2   Field    14928 non-null  object
 3   Channel  14928 non-null  object
 4   Cycle    14928 non-null  int64
 5   Area     14928 non-null  float64
 6   IntDen   14928 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 816.5+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11592 entries, 0 to 11591
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  11592 non-null  object
 1   Well     11592 non-null  object
 2   Field    11592 non-null  object
 3   Channel  11592 non-null  object
 4   Cycle    11592 non-null  int64
 5   Area     11592 non-null  float64
 6   IntDen   11592 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 634.1+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5448 entries, 0 to 5447
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  5448 non-null   object
 1   Well     5448 non-null   object
 2   Field    5448 non-null   object
 3   Channel  5448 non-null   object
 4   Cycle    5448 non-null   int64
 5   Area     5448 non-null   float64
 6   IntDen   5448 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 298.1+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10128 entries, 0 to 10127
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  10128 non-null  object
 1   Well     10128 non-null  object
 2   Field    10128 non-null  object
 3   Channel  10128 non-null  object
 4   Cycle    10128 non-null  int64
 5   Area     10128 non-null  float64
 6   IntDen   10128 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 554.0+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16704 entries, 0 to 16703
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  16704 non-null  object
 1   Well     16704 non-null  object
 2   Field    16704 non-null  object
 3   Channel  16704 non-null  object
 4   Cycle    16704 non-null  int64
 5   Area     16704 non-null  float64
 6   IntDen   16704 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 913.6+ KB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19176 entries, 0 to 19175
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  19176 non-null  object
 1   Well     19176 non-null  object
 2   Field    19176 non-null  object
 3   Channel  19176 non-null  object
 4   Cycle    19176 non-null  int64
 5   Area     19176 non-null  float64
 6   IntDen   19176 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.0+ MB
None

 * * * * * * * * * * * * * * * * * * * * * * * * * *

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16224 entries, 0 to 16223
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Cell ID  16224 non-null  object
 1   Well     16224 non-null  object
 2   Field    16224 non-null  object
 3   Channel  16224 non-null  object
 4   Cycle    16224 non-null  int64
 5   Area     16224 non-null  float64
 6   IntDen   16224 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 887.4+ KB
None

In [7]:
for df in df_Nuc[:n]:
    print('\n', '* ' * 26, '\n')
    print(df['Channel'].value_counts())

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    5694
Cy5     5694
DAPI    5694
Cy3     5694
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    2106
Cy3     2106
DAPI    2106
Cy5     2106
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    5166
Cy5     5166
DAPI    5166
Cy3     5166
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4608
DAPI    4608
Cy5     4608
Cy3     4608
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    2100
Cy3     2100
DAPI    2100
Cy5     2100
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3060
DAPI    3060
Cy5     3060
Cy3     3060
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    5010
DAPI    5010
Cy5     5010
Cy3     5010
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4392
DAPI    4392
Cy5     4392
Cy3     4392
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4080
DAPI    4080
Cy5     4080
Cy3     4080
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3930
DAPI    3930
Cy5     3930
Cy3     3930
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3192
DAPI    3192
Cy5     3192
Cy3     3192
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3558
DAPI    3558
Cy5     3558
Cy3     3558
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3276
DAPI    3276
Cy5     3276
Cy3     3276
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    2562
Cy3     2562
DAPI    2562
Cy5     2562
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4350
DAPI    4350
Cy5     4350
Cy3     4350
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3354
DAPI    3354
Cy5     3354
Cy3     3354
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4218
DAPI    4218
Cy5     4218
Cy3     4218
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    6054
Cy5     6054
DAPI    6054
Cy3     6054
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4146
DAPI    4146
Cy5     4146
Cy3     4146
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    1566
Cy3     1566
DAPI    1566
Cy5     1566
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    3732
DAPI    3732
Cy5     3732
Cy3     3732
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    2898
DAPI    2898
Cy5     2898
Cy3     2898
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    1362
Cy3     1362
DAPI    1362
Cy5     1362
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    2532
Cy3     2532
DAPI    2532
Cy5     2532
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4176
DAPI    4176
Cy5     4176
Cy3     4176
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4794
DAPI    4794
Cy5     4794
Cy3     4794
Name: Channel, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

FITC    4056
DAPI    4056
Cy5     4056
Cy3     4056
Name: Channel, dtype: int64

In [8]:
for df in df_Nuc[:n]:
    print('\n', '* ' * 26, '\n')
    print(df['Cycle'].value_counts())

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    3796
5    3796
4    3796
3    3796
2    3796
1    3796
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    1404
5    1404
4    1404
3    1404
2    1404
1    1404
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    3444
5    3444
4    3444
3    3444
2    3444
1    3444
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    3072
5    3072
4    3072
3    3072
2    3072
1    3072
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    1400
5    1400
4    1400
3    1400
2    1400
1    1400
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2040
5    2040
4    2040
3    2040
2    2040
1    2040
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    3340
5    3340
4    3340
3    3340
2    3340
1    3340
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2928
5    2928
4    2928
3    2928
2    2928
1    2928
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2720
5    2720
4    2720
3    2720
2    2720
1    2720
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2620
5    2620
4    2620
3    2620
2    2620
1    2620
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2128
5    2128
4    2128
3    2128
2    2128
1    2128
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2372
5    2372
4    2372
3    2372
2    2372
1    2372
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2184
5    2184
4    2184
3    2184
2    2184
1    2184
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    1708
5    1708
4    1708
3    1708
2    1708
1    1708
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2900
5    2900
4    2900
3    2900
2    2900
1    2900
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2236
5    2236
4    2236
3    2236
2    2236
1    2236
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2812
5    2812
4    2812
3    2812
2    2812
1    2812
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    4036
5    4036
4    4036
3    4036
2    4036
1    4036
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2764
5    2764
4    2764
3    2764
2    2764
1    2764
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

3    1044
6    1044
2    1044
5    1044
1    1044
4    1044
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2488
5    2488
4    2488
3    2488
2    2488
1    2488
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    1932
5    1932
4    1932
3    1932
2    1932
1    1932
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

3    908
6    908
2    908
5    908
1    908
4    908
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    1688
5    1688
4    1688
3    1688
2    1688
1    1688
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2784
5    2784
4    2784
3    2784
2    2784
1    2784
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    3196
5    3196
4    3196
3    3196
2    3196
1    3196
Name: Cycle, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

6    2704
5    2704
4    2704
3    2704
2    2704
1    2704
Name: Cycle, dtype: int64

In [9]:
for df in df_Nuc[:n]:
    print('\n', '* ' * 26, '\n')
    print(df['Cell ID'].value_counts())

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0405-0391    24
0505-0506    24
0310-0288    24
0046-0073    24
0039-0062    24
             ..
0633-0648    24
0736-0736    24
0721-0722    24
0159-0182    24
0662-0669    24
Name: Cell ID, Length: 949, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0043-0100    24
0346-1026    24
0298-0863    24
0172-0343    24
0341-1011    24
             ..
0274-0760    24
0167-0335    24
0169-0338    24
0325-0956    24
0188-0384    24
Name: Cell ID, Length: 351, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0265-0274    24
0342-0326    24
0150-0159    24
0390-0375    24
0791-0838    24
             ..
0672-0706    24
0644-0674    24
0179-0191    24
0726-0769    24
0248-0260    24
Name: Cell ID, Length: 861, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0096-0093    24
0221-0267    24
0066-0078    24
0252-0310    24
0693-0922    24
             ..
0120-0126    24
0005-0030    24
0471-0604    24
0738-0981    24
0002-0031    24
Name: Cell ID, Length: 768, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0090-0199    24
0106-0265    24
0119-0297    24
0153-0369    24
0222-0654    24
             ..
0052-0117    24
0142-0342    24
0261-0792    24
0036-0091    24
0196-0552    24
Name: Cell ID, Length: 350, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0441-0899    24
0509-1035    24
0320-0553    24
0261-0440    24
0359-0689    24
             ..
0080-0146    24
0020-0050    24
0108-0174    24
0138-0244    24
0130-0217    24
Name: Cell ID, Length: 510, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0252-0183    24
0286-0213    24
0610-0662    24
0048-0056    24
0112-0101    24
             ..
0225-0163    24
0340-0271    24
0601-0636    24
0790-0951    24
0418-0358    24
Name: Cell ID, Length: 835, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0664-0967    24
0360-0476    24
0419-0540    24
0168-0215    24
0025-0049    24
             ..
0135-0183    24
0401-0528    24
0326-0447    24
0100-0165    24
0536-0732    24
Name: Cell ID, Length: 732, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0323-0430    24
0083-0127    24
0044-0091    24
0527-0753    24
0263-0352    24
             ..
0283-0386    24
0062-0101    24
0221-0274    24
0093-0136    24
0648-0998    24
Name: Cell ID, Length: 680, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0556-0794    24
0250-0277    24
0212-0238    24
0104-0129    24
0528-0703    24
             ..
0468-0557    24
0058-0072    24
0479-0618    24
0522-0690    24
0387-0423    24
Name: Cell ID, Length: 655, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0125-0117    24
0283-0360    24
0421-0704    24
0191-0192    24
0291-0390    24
             ..
0108-0104    24
0081-0083    24
0278-0356    24
0091-0092    24
0523-1025    24
Name: Cell ID, Length: 532, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0167-0171    24
0305-0367    24
0460-0705    24
0439-0606    24
0215-0246    24
             ..
0353-0441    24
0010-0041    24
0267-0311    24
0216-0249    24
0004-0031    24
Name: Cell ID, Length: 593, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0234-0369    24
0288-0482    24
0145-0176    24
0401-0755    24
0428-0840    24
             ..
0096-0114    24
0460-0915    24
0455-0912    24
0144-0190    24
0471-0927    24
Name: Cell ID, Length: 546, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0155-0263    24
0044-0100    24
0025-0075    24
0138-0214    24
0222-0463    24
             ..
0175-0290    24
0118-0180    24
0426-1035    24
0201-0347    24
0247-0555    24
Name: Cell ID, Length: 427, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0461-0672    24
0467-0683    24
0442-0652    24
0371-0543    24
0648-0963    24
             ..
0611-0916    24
0590-0885    24
0082-0107    24
0480-0698    24
0208-0196    24
Name: Cell ID, Length: 725, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0168-0233    24
0528-0996    24
0042-0072    24
0237-0353    24
0466-0816    24
             ..
0313-0459    24
0520-0977    24
0108-0144    24
0326-0477    24
0289-0445    24
Name: Cell ID, Length: 559, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0048-0048    24
0522-0768    24
0502-0720    24
0459-0603    24
0342-0439    24
             ..
0692-1030    24
0520-0762    24
0630-0982    24
0257-0258    24
0612-0966    24
Name: Cell ID, Length: 703, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0340-0307    24
0626-0580    24
0733-0750    24
0691-0679    24
0959-0995    24
             ..
0603-0547    24
0379-0334    24
0033-0053    24
0371-0339    24
0417-0368    24
Name: Cell ID, Length: 1009, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0175-0181    24
0179-0180    24
0124-0128    24
0038-0049    24
0614-0888    24
             ..
0354-0356    24
0634-0954    24
0226-0222    24
0410-0410    24
0688-1033    24
Name: Cell ID, Length: 691, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0256-1031    24
0143-0394    24
0095-0199    24
0096-0202    24
0140-0373    24
             ..
0061-0109    24
0076-0151    24
0054-0086    24
0223-0826    24
0252-1026    24
Name: Cell ID, Length: 261, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0140-0185    24
0397-0536    24
0522-0859    24
0492-0814    24
0383-0527    24
             ..
0087-0139    24
0575-0926    24
0320-0400    24
0289-0343    24
0437-0637    24
Name: Cell ID, Length: 622, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0318-0663    24
0184-0403    24
0116-0250    24
0212-0441    24
0317-0666    24
             ..
0158-0345    24
0429-0915    24
0407-0862    24
0351-0739    24
0146-0314    24
Name: Cell ID, Length: 483, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0092-0264    24
0108-0334    24
0215-1014    24
0043-0164    24
0045-0164    24
             ..
0021-0117    24
0023-0123    24
0088-0233    24
0042-0165    24
0035-0150    24
Name: Cell ID, Length: 227, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0304-0698    24
0174-0403    24
0365-0864    24
0097-0147    24
0414-1030    24
             ..
0284-0641    24
0361-0855    24
0406-1017    24
0153-0287    24
0117-0183    24
Name: Cell ID, Length: 422, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0289-0470    24
0143-0199    24
0396-0593    24
0254-0397    24
0179-0241    24
             ..
0076-0111    24
0609-0894    24
0629-0933    24
0337-0520    24
0467-0672    24
Name: Cell ID, Length: 696, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0544-0675    24
0392-0511    24
0034-0054    24
0620-0759    24
0332-0428    24
             ..
0701-0898    24
0007-0036    24
0140-0184    24
0115-0130    24
0562-0685    24
Name: Cell ID, Length: 799, dtype: int64

 * * * * * * * * * * * * * * * * * * * * * * * * * *

0601-0946    24
0482-0762    24
0618-0984    24
0300-0443    24
0007-0028    24
             ..
0341-0518    24
0514-0807    24
0357-0560    24
0211-0316    24
0107-0174    24
Name: Cell ID, Length: 676, dtype: int64

In [10]:
for df in df_Nuc[:n]:
    print('\n', '* ' * 26, '\n')
    print('Total cells in well {} field {}: {}'\
          .format(df.Well[0], df.Field[0], 
                  int(df.shape[0] / df['Cell ID'].value_counts()[0])))

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 1: 949

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 2: 351

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 3: 861

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 4: 768

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 5: 350

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 6: 510

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 7: 835

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 8: 732

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B02 field 9: 680

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 1: 655

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 2: 532

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 3: 593

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 4: 546

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 5: 427

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 6: 725

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 7: 559

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 8: 703

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B03 field 9: 1009

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 1: 691

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 2: 261

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 3: 622

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 4: 483

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 5: 227

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 6: 422

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 7: 696

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 8: 799

 * * * * * * * * * * * * * * * * * * * * * * * * * *

Total cells in well B04 field 9: 676